---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: using_strings
    run_list:
      - recipe[test_dots::using_strings]
    attributes:
  - name: using_dots
    run_list:
      - recipe[test_dots::using_dots]
